runtime: nodejs18

handlers:
  - url: /
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

  - url: /profile
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

  - url: /auth/login
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

  - url: /auth/signup
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

  - url: /auth/forgot-password
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

  - url: /(.*)
    static_files: frontend/dist/\1
    upload: frontend/dist/(.*)
